/*
 * WARNING: do not edit!
 * Generated by CMake
 * via configuration.h.cmake.in
 *
 * Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_CONFIGURATION_H
#define OPENSSL_CONFIGURATION_H
#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef OPENSSL_ALGORITHM_DEFINES
#error OPENSSL_ALGORITHM_DEFINES no longer supported
#endif

#define EXTERNALCMAKE_HAS_SYSDEFINE
#ifdef EXTERNALCMAKE_HAS_SYSDEFINE
#ifndef OPENSSL_SYS_MACOSX
#define OPENSSL_SYS_MACOSX 1
#endif
#undef EXTERNALCMAKE_HAS_SYSDEFINE
#endif

#define EXTERNALCMAKE_MIN_API_LEVEL
#ifdef EXTERNALCMAKE_MIN_API_LEVEL
#define OPENSSL_CONFIGURED_API 30000
#undef EXTERNALCMAKE_MIN_API_LEVEL
#else
#define OPENSSL_CONFIGURED_API 30000
#endif

#ifndef OPENSSL_THREADS
#define OPENSSL_THREADS
#endif

/* #undef OPENSSL_RAND_SEED_GETRANDOM */
/* #undef OPENSSL_RAND_SEED_DEVRANDOM */
#define OPENSSL_RAND_SEED_OS
/* #undef OPENSSL_RAND_SEED_EGD */
/* #undef OPENSSL_RAND_SEED_NONE */
/* #undef OPENSSL_RAND_SEED_RDCPU */
/* #undef OPENSSL_RAND_SEED_LIBRANDOM */

#define OPENSSL_NO_ACVP_TESTS
/* #undef OPENSSL_NO_AES */
#define OPENSSL_NO_AFALGENG
/* #undef OPENSSL_NO_APPS */
/* #undef OPENSSL_NO_ARGON2 */
/* #undef OPENSSL_NO_ARIA */
#define OPENSSL_NO_ASAN
/* #undef OPENSSL_NO_ASM */
/* #undef OPENSSL_NO_ASN1 */
/* #undef OPENSSL_NO_ASYNC */
/* #undef OPENSSL_NO_ATEXIT */
#define OPENSSL_NO_AUTOALGINIT
/* #undef OPENSSL_NO_AUTOERRINIT */
/* #undef OPENSSL_NO_AUTOLOAD_CONFIG */
/* #undef OPENSSL_NO_BF */
/* #undef OPENSSL_NO_BIO */
/* #undef OPENSSL_NO_BLAKE2 */
/* #undef OPENSSL_NO_BN */
#define OPENSSL_NO_BROTLI
#define OPENSSL_NO_BROTLI_DYNAMIC
/* #undef OPENSSL_NO_BUFFER */
/* #undef OPENSSL_NO_BULK */
/* #undef OPENSSL_NO_CACHED_FETCH */
/* #undef OPENSSL_NO_CAMELLIA */
/* #undef OPENSSL_NO_CAPIENG */
/* #undef OPENSSL_NO_CAST */
/* #undef OPENSSL_NO_CHACHA */
/* #undef OPENSSL_NO_CMAC */
#define OPENSSL_NO_CMP
/* #undef OPENSSL_NO_CMS */
/* #undef OPENSSL_NO_COMP */
/* #undef OPENSSL_NO_CONF */
#define OPENSSL_NO_CRMF
#define OPENSSL_NO_CRYPTO_MDEBUG
/* #undef OPENSSL_NO_CT */
/* #undef OPENSSL_NO_DEFAULT_THREAD_POOL */
#define OPENSSL_NO_DEMOS
/* #undef OPENSSL_NO_DEPRECATED */
/* #undef OPENSSL_NO_DEPRECATED_0_9_8 */
/* #undef OPENSSL_NO_DEPRECATED_1_0_0 */
/* #undef OPENSSL_NO_DEPRECATED_1_0_1 */
/* #undef OPENSSL_NO_DEPRECATED_1_0_2 */
/* #undef OPENSSL_NO_DEPRECATED_1_1_0 */
/* #undef OPENSSL_NO_DEPRECATED_1_1_1 */
/* #undef OPENSSL_NO_DEPRECATED_3_0 */
/* #undef OPENSSL_NO_DEPRECATED_3_0_0 */
/* #undef OPENSSL_NO_DES */
#define OPENSSL_NO_DEVCRYPTOENG
/* #undef OPENSSL_NO_DGRAM */
/* #undef OPENSSL_NO_DH */
/* #undef OPENSSL_NO_DOCS */
/* #undef OPENSSL_NO_DSA */
#define OPENSSL_NO_DSO
/* #undef OPENSSL_NO_DTLS */
#define OPENSSL_NO_DTLS1
/* #undef OPENSSL_NO_DTLS1_2 */
/* #undef OPENSSL_NO_DTLS1_2_METHOD */
/* #undef OPENSSL_NO_DTLS1_METHOD */
#define OPENSSL_NO_DYNAMIC_ENGINE
/* #undef OPENSSL_NO_EC */
/* #undef OPENSSL_NO_EC2M */
/* #undef OPENSSL_NO_ECDH */
/* #undef OPENSSL_NO_ECDSA */
/* #undef OPENSSL_NO_ECX */
#define OPENSSL_NO_EC_NISTP_64_GCC_128
#define OPENSSL_NO_EGD
/* #undef OPENSSL_NO_ENCODE_DECODE */
/* #undef OPENSSL_NO_ENGINE */
/* #undef OPENSSL_NO_ERR */
/* #undef OPENSSL_NO_ESS */
/* #undef OPENSSL_NO_EVP */
#define OPENSSL_NO_EXTERNAL_TESTS
/* #undef OPENSSL_NO_FFC */
/* #undef OPENSSL_NO_FILENAMES */
#define OPENSSL_NO_FIPS
/* #undef OPENSSL_NO_FIPS_POST */
#define OPENSSL_NO_FIPS_SECURITYCHECKS
#define OPENSSL_NO_FUZZ_AFL
#define OPENSSL_NO_FUZZ_LIBFUZZER
/* #undef OPENSSL_NO_GOST */
#define OPENSSL_NO_H3DEMO
/* #undef OPENSSL_NO_HASHTABLE */
/* #undef OPENSSL_NO_HMAC */
/* #undef OPENSSL_NO_HPKE */
/* #undef OPENSSL_NO_HTTP */
/* #undef OPENSSL_NO_HW */
/* #undef OPENSSL_NO_IDEA */
/* #undef OPENSSL_NO_INTEGRITY_ONLY_CIPHERS */
#define OPENSSL_NO_JITTER
/* #undef OPENSSL_NO_KDF */
#define OPENSSL_NO_KTLS
/* #undef OPENSSL_NO_LEGACY */
/* #undef OPENSSL_NO_LHASH */
#define OPENSSL_NO_LOADERENG
/* #undef OPENSSL_NO_MAKEDEPEND */
#define OPENSSL_NO_MD2
/* #undef OPENSSL_NO_MD4 */
/* #undef OPENSSL_NO_MD5 */
/* #undef OPENSSL_NO_MDC2 */
/* #undef OPENSSL_NO_MODES */
#define OPENSSL_NO_MSAN
/* #undef OPENSSL_NO_MULTIBLOCK */
#define OPENSSL_NO_NASM
/* #undef OPENSSL_NO_NEXTPROTONEG */
/* #undef OPENSSL_NO_OBJECTS */
/* #undef OPENSSL_NO_OCB */
#define OPENSSL_NO_OCSP
/* #undef OPENSSL_NO_PADLOCKENG */
/* #undef OPENSSL_NO_PEM */
#define OPENSSL_NO_PIE
/* #undef OPENSSL_NO_PINSHARED */
/* #undef OPENSSL_NO_PKCS12 */
/* #undef OPENSSL_NO_PKCS7 */
/* #undef OPENSSL_NO_POLY1305 */
/* #undef OPENSSL_NO_POSIX_IO */
/* #undef OPENSSL_NO_PROPERTY */
/* #undef OPENSSL_NO_PSK */
/* #undef OPENSSL_NO_QLOG */
/* #undef OPENSSL_NO_QUIC */
/* #undef OPENSSL_NO_RAND */
/* #undef OPENSSL_NO_RC2 */
/* #undef OPENSSL_NO_RC4 */
#define OPENSSL_NO_RC5
/* #undef OPENSSL_NO_RDRAND */
/* #undef OPENSSL_NO_RFC3779 */
/* #undef OPENSSL_NO_RMD160 */
/* #undef OPENSSL_NO_RSA */
/* #undef OPENSSL_NO_SCRYPT */
#define OPENSSL_NO_SCTP
/* #undef OPENSSL_NO_SECURE_MEMORY */
/* #undef OPENSSL_NO_SEED */
/* #undef OPENSSL_NO_SHA */
/* #undef OPENSSL_NO_SIPHASH */
/* #undef OPENSSL_NO_SIV */
/* #undef OPENSSL_NO_SM2 */
/* #undef OPENSSL_NO_SM2_PRECOMP */
/* #undef OPENSSL_NO_SM3 */
/* #undef OPENSSL_NO_SM4 */
/* #undef OPENSSL_NO_SOCK */
/* #undef OPENSSL_NO_SRP */
/* #undef OPENSSL_NO_SRTP */
#define OPENSSL_NO_SSL
#define OPENSSL_NO_SSL3
#define OPENSSL_NO_SSL3_METHOD
/* #undef OPENSSL_NO_SSL_TRACE */
/* #undef OPENSSL_NO_STACK */
/* #undef OPENSSL_NO_STATIC_ENGINE */
/* #undef OPENSSL_NO_STDIO */
/* #undef OPENSSL_NO_STORE */
/* #undef OPENSSL_NO_TESTS */
#define OPENSSL_NO_TFO
/* #undef OPENSSL_NO_THREAD */
/* #undef OPENSSL_NO_THREADS */
/* #undef OPENSSL_NO_THREAD_POOL */
/* #undef OPENSSL_NO_TLS */
/* #undef OPENSSL_NO_TLS1 */
/* #undef OPENSSL_NO_TLS1_1 */
/* #undef OPENSSL_NO_TLS1_1_METHOD */
/* #undef OPENSSL_NO_TLS1_2 */
/* #undef OPENSSL_NO_TLS1_2_METHOD */
/* #undef OPENSSL_NO_TLS1_3 */
/* #undef OPENSSL_NO_TLS1_METHOD */
#define OPENSSL_NO_TRACE
/* #undef OPENSSL_NO_TS */
/* #undef OPENSSL_NO_TXT_DB */
#define OPENSSL_NO_UBSAN
/* #undef OPENSSL_NO_UI_CONSOLE */
#define OPENSSL_NO_UNIT_TEST
/* #undef OPENSSL_NO_UNSTABLE_QLOG */
#define OPENSSL_NO_UPLINK
#define OPENSSL_NO_WEAK_SSL_CIPHERS
/* #undef OPENSSL_NO_WHIRLPOOL */
#define OPENSSL_NO_WINSTORE
/* #undef OPENSSL_NO_X509 */
/* #undef OPENSSL_NO_ZLIB */
#define OPENSSL_NO_ZLIB_DYNAMIC
#define OPENSSL_NO_ZSTD
#define OPENSSL_NO_ZSTD_DYNAMIC

/* Generate 80386 code? */
/* #undef I386_ONLY */

/*
 * The following are cipher-specific, but are part of the public API.
 */
#if !defined(OPENSSL_SYS_UEFI)
/* #undef BN_LLONG */
/* Only one for the following should be defined */
#define SIXTY_FOUR_BIT_LONG
/* #undef SIXTY_FOUR_BIT */
/* #undef THIRTY_TWO_BIT */
#endif

#define RC4_INT unsigned int

#ifdef __cplusplus
}
#endif

#endif
